#===================================================
# Description: Build v8 enginer using GitHub Actions
# Author: t1an5t
#===================================================


name: BUILD v8

on:
  push:
    branches: [ master ]
  # watch:
  #   types: started

env:
  PATCH_FLAG: true
  COMMIT: 6dc88c191f5ecc5389dc26efa3ca0907faef3598
  DEPOT_UPLOAD: true
  SRC_UPLOAD: true
  BINARY_UPLOAD: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id 	
    
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    # init ubuntu1804 environment
    - name: init env
      run: |
        sudo apt-get update
        sudo apt-get -y install pkg-config git subversion curl wget build-essential python xz-utils zip p7zip-full
    
    - name: get ninja
      run: |
        sudo apt-get install libtool autoconf
        git clone https://github.com/skvadrik/re2c.git re2c
        cd re2c
        mkdir -p m4
        ./autogen.sh && ./configure --prefix=/usr && make
        sudo make install
        re2c -v
        cd ..
        wget https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-linux.zip -O ninja-linux.zip
        unzip ninja-linux.zip
        echo export PATH=\"\$PATH:`pwd`/ninja\" >> ~/.bash_profile
        echo "::warning file=cowtransfer.com::$(cat ~/.bash_profile)"
         echo "::warning file=cowtransfer.com::$(ls -al)"
    
